// Style Dictionary v4: Figma variables (DTCG JSON) -> Tailwind v4 @theme.
// Source of truth is tokens/figma.tokens.json, exported from the Ledger Design System Figma file.
// Every utility class the app can use comes from this file. There is no default Tailwind palette.
import StyleDictionary from "style-dictionary";

const WEIGHT = { Regular: 400, Medium: 500, "Semi Bold": 600, Bold: 700 };

function cssLines(tokens) {
  const out = [];
  for (const t of tokens) {
    const [group, ...rest] = t.path;
    const name = rest.join("-");
    const v = t.$value ?? t.value;
    switch (group) {
      case "primitives":
        break; // hidden: only semantic roles reach the app
      case "semantic":
        out.push(`  --color-${name}: ${v};`);
        break;
      case "layout":
        // Spacing: Tailwind v4 numeric utilities are multiples of --spacing (4px), so p-6 = 24px.
        // The Figma steps (4 8 12 16 24 32 48 64) are the allowed multiples; scripts/check-raw-values.mjs enforces them.
        if (rest[0] === "space") { if (rest[1] === "4") out.push(`  --spacing: 4px;`); }
        else if (rest[0] === "radius") out.push(`  --radius-${rest[1]}: ${v}px;`);
        else if (rest[0] === "size") out.push(`  --size-${rest[1]}: ${v}px;`);
        else if (rest[0] === "border") out.push(`  --border-${rest[1]}: ${v}px;`);
        break;
      case "typography":
        if (rest[0] === "font") out.push(`  --font-sans: "${v}", system-ui, sans-serif;`);
        else if (rest[0] === "weight") out.push(`  --font-weight-${rest[1]}: ${WEIGHT[v] ?? v};`);
        else if (rest[0] === "size") out.push(`  --font-size-${rest[1]}: ${v}px;`);
        else if (rest[0] === "leading") out.push(`  --leading-${rest[1]}: ${v}px;`);
        break;
      case "textstyles": {
        // Tailwind v4 composite text utility: text-h1 sets size, line height, weight and tracking.
        out.push(`  --text-${name}: ${v.fontSize}px;`);
        out.push(`  --text-${name}--line-height: ${v.lineHeight}px;`);
        out.push(`  --text-${name}--font-weight: ${WEIGHT[v.fontWeight] ?? v.fontWeight};`);
        out.push(`  --text-${name}--letter-spacing: ${parseFloat(v.letterSpacing) / 100}em;`);
        break;
      }
    }
  }
  return out;
}

StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) =>
    `/* Generated by Style Dictionary from tokens/figma.tokens.json. Do not edit by hand. */\n` +
    `@theme {\n  --color-*: initial;\n  --font-*: initial;\n  --radius-*: initial;\n  --text-*: initial;\n  --shadow-*: initial;\n` +
    cssLines(dictionary.allTokens).join("\n") +
    `\n}\n`,
});

StyleDictionary.registerFormat({
  name: "json/ledger-map",
  format: ({ dictionary }) => {
    const map = {};
    for (const t of dictionary.allTokens) {
      if (t.path[0] === "primitives") continue;
      const web = t.$extensions?.["com.figma"]?.codeSyntax?.WEB;
      map[t.path.join("/")] = { value: t.$value ?? t.value, css: web ?? null };
    }
    return JSON.stringify(map, null, 2) + "\n";
  },
});

export default {
  source: ["tokens/figma.tokens.json"],
  platforms: {
    css: {
      transforms: ["attribute/cti", "name/kebab"],
      buildPath: "src/tokens/",
      files: [{ destination: "theme.css", format: "css/tailwind-theme" }],
    },
    json: {
      transforms: ["attribute/cti", "name/kebab"],
      buildPath: "src/tokens/",
      files: [{ destination: "tokens.json", format: "json/ledger-map" }],
    },
  },
};
